# generated by datamodel-codegen (hand-aligned reference copy; regenerate with the Skill if it differs)
#   filename:  meeting-portal-api.yaml

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class TranscriptUploadRequest(BaseModel):
    title: str
    meetingDate: date
    rawText: str


class TranscriptUploadResponse(BaseModel):
    meetingId: str


class Sentiment(Enum):
    positive = 'positive'
    neutral = 'neutral'
    negative = 'negative'


class MeetingSummary(BaseModel):
    meetingId: str
    summary: str
    decisions: List[str]
    sentiment: Optional[Sentiment] = Field(None, description='會議整體氛圍')
    generatedAt: datetime = Field(..., description='摘要產生時間(UTC)')


class Priority(Enum):
    High = 'High'
    Medium = 'Medium'
    Low = 'Low'


class ActionItem(BaseModel):
    owner: str
    action: str
    dueDate: Optional[date] = None
    priority: Priority


class Risk(BaseModel):
    label: str
    detail: Optional[str] = None


class MatchType(Enum):
    literal = 'literal'
    semantic = 'semantic'


class SearchResult(BaseModel):
    speaker: str
    excerpt: str
    matchType: MatchType


class ErrorResponse(BaseModel):
    message: str
